# Generated by Django 4.2.5 on 2023-09-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_gender', models.CharField(max_length=10)),
                ('emp_dob', models.DateField()),
                ('emp_dept', models.CharField(max_length=100)),
                ('emp_email', models.EmailField(max_length=100, unique=True)),
                ('emp_contactno', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'employee_table',
            },
        ),
    ]
