# Generated by Django 4.2.5 on 2023-09-08 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_rename_contact_registration_contactno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='contactno',
            new_name='contact',
        ),
    ]
