# Generated by Django 4.2.5 on 2023-09-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_rename_contactno_registration_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='dateofbirth',
            field=models.CharField(max_length=20),
        ),
    ]
