# Generated by Django 4.2.5 on 2023-09-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_alter_registration_dateofbirth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=50)),
                ('dept_hod', models.CharField(max_length=50)),
                ('dept_location', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'department_table',
            },
        ),
    ]
